* Question 1.1

Draw the environment diagram that results from executing the code below.

#+BEGIN_SRC python
from operator import add

six = 1

def ty(one, a):
    fall = one(a, six)
    return fall

six = ty(add, 6)
fall = ty(add, 6)
#+END_SRC

** Global Frame
   add = func add(...) [parent=Globabl]
   six = 7
   ty = func ty(one, a) [parent=Global]
   fall = 13
** f1: ty [parent=Global]
   one = func add(...) [parent=Globabl]
   a = 6
   fall = 7
   return value = 7
** f2: ty [parent=Global]
   one = func add(...) [parent=Globabl]
   a = 6
   fall = 13
   return value = 13

* Question 1.2

Draw the environment diagram that results from executing the code below.

#+BEGIN_SRC python
def curry2(h):
    def f(x):
        def g(y):
            return h(x, y)
        return g
    return f

make_adder = curry2(lambda x, y: x + y)
add_three = make_adder(3)
five = add_three(2)
#+END_SRC

** Global Frame
   curry2 = func curry2(h) [parent=Global]
   make_adder = func f(x) [parent=f1]
   add_three = func g(y) [parent=f2]
   five = 5
** f1: curry2 [parent=Global]
   h = func λ(x, y) [parent=Global]
   f = func f(x) [parent=f1]
   return value = func f(x) [parent=f1]
** f2: f [parent=f1]
   x = 3
   g = func g(y) [parent=f2]
   return value = func g(y) [parent=f2]
** f3: g [parent=f2]
   y = 2
   return value = 5
** f4: λ [parent=Global]
   x = 3
   y = 2
   return value = 5
* Question 1.3

Draw the environment diagram that results from executing the code below.

#+BEGIN_SRC python
n = 7

def f(x):
    n = 8
    return x + 1

def g(x):
    n = 9
    def h():
        return x + 1
    return h

def f(f, x):
    return f(x + n)

f = f(g, n)
g = (lambda y: y())(f)
#+END_SRC

** Global Frame
   n = 7
   f =  func h() [parent=f2]
   g = 15
** f1: f(f, x) [parent=Global]
   f = func g(x) [parent=Global]
   x = 7
   return value = func h() [parent=f2]
** f2: g(x) [parent=Global]
   x = 14
   n = 9
   h = func h() [parent=f2]
   return value = func h() [parent=f2]
** f3: λ(y) [parent=Global]
   y = func h() [parent=f2]
   return value = 15
** f4 h() [parent=f2]
   return value = 15
* Question 1.4

Draw the environment diagram that results from executing the code below.

#+BEGIN_SRC python
y = "y"
h = y
def y(y):
    h = "h"
    if y == h:
        return y + "i"
    y = lambda y: y(h)
    return lambda h: y(h)
y = y(y)(y)
#+END_SRC

** Global Frame
   y = "hi"
   h = "y"
** f1: y [parent=Global]
   y = func λ(y) [parent=f1]
   h = "h"
   return value = func λ(h) [parent=f1]
** f2: λ [parent=f1]
   h = func y(y) [parent=f1]
** f3: λ [parent=f1]
   y = func y(y) [parent=Global]
** f4: y [parent=Global]
   y = "h"
   h = "h"
   return value = "h"
